# Generated by Django 3.0.2 on 2020-01-15 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imported', models.BooleanField(verbose_name='Importação')),
                ('name', models.CharField(max_length=100, verbose_name='Nome')),
                ('ncm', models.CharField(max_length=8, verbose_name='NCM')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Preço')),
                ('current_stock', models.IntegerField(verbose_name='Estoque atual')),
                ('minimum_stock', models.PositiveIntegerField(default=0, verbose_name='Estoque Mínimo')),
            ],
            options={
                'ordering': ('name',),
            },
        ),
    ]
